### ISSUE TITLE
Data for the "Energy Flow" diagram

### ISSUE THREAD

**Issue by gretamaltsenko** [innoTUgrid/backend#26]
- Im Frontend werden Daten zur Aggregation benötigt (aus dem energy consumer endpoint)
- bei den rohdaten sollen aggregate und consumption geliefert werden
- alles soll in einer einheit zurückgegeben werden (kw/h)

**Comment by gretamaltsenko** [comment]
@Tobiasloch hier die infos zu energy flow

**Comment by gretamaltsenko** [comment]
@nymphbox @OleFass @tomijange bitte priorisieren!

**Comment by tomijange** [comment]
961f50b
You have to reimport example data (e.g. by wiping your db)
