### ISSUE TITLE
Show coal types separately in Energy Mix diagram

### ISSUE THREAD

**Issue by gretamaltsenko** [innoTUgrid/backend#41]
Wir benötigen für das o. g. Diagramm separate Daten zur Braun- und Steinkohle. Diese kommen im Frontend aggregiert an. 

@tomijange @OleFass @nymphbox

**Comment by Tobiasloch** [comment]
hard coal und brown coal have both the carrier coal, but should have its own.

> {
>             "id": 5,
>             **"identifier": "brown coal",**
>             "unit": "mwh",
>             **"carrier": "coal"**,
>             "min_timestamp": "2019-01-01T00:00:00Z",
>             "max_timestamp": "2019-08-31T23:45:00Z"
>         },
>         {
>             "id": 6,
>             **"identifier": "hard coal"**,
>             "unit": "mwh",
>             **"carrier": "coal"**,
>             "min_timestamp": "2019-01-01T00:00:00Z",
>             "max_timestamp": "2019-08-31T23:45:00Z"
>         },

**Comment by tomijange** [comment]
Fixed in 961f50b5450582624f228338a99337e11452e048
