### ISSUE TITLE
In the /meta and /ts endpoint are the data inconsistent

### ISSUE THREAD

**Issue by Tobiasloch** [innoTUgrid/backend#47]
the ts and the meta enpoint both return meta data, but for the same identifier the meta info differs.

from /meta:
> {
>             "id": 1,
>             "identifier": "production_of_chp",
>             "unit": "kw",
>             "carrier": "biogas",
>             "min_timestamp": "2019-01-01T00:00:00Z",
>             "max_timestamp": "2019-08-31T23:45:00Z"
>         },

from /ts
> "meta": {
>         "id": 1,
>         "identifier": "production_of_chp",
>         "unit": "kw",
>         "carrier": "biogas",
>         "consumption": false
>     }

**Comment by tomijange** [comment]
cecb636942786855c8bde2274b5ed5ac19233197
/meta now has "consumption"
min/max timestamps are not calculated
