### ISSUE TITLE
Specify ON_DELETE behavior for foreign key relations 

### ISSUE THREAD

**Issue by nymphbox** [innoTUgrid/backend#50]
Affects tables meta, ts, emission factor. Appropriate constraint will depend on specific table

**Comment by tomijange** [comment]
current on delete behaviours seem fine for me, emission_factor and energy_carrier are mostly static anyway. 
`ts` has no dependency, when deleting from `meta` we could delete the entire timeseries, but would do it in backend for readability reasons
