### ISSUE TITLE
Datapoints from timeseries endpoint do not lie in the given time interval

### ISSUE THREAD

**Issue by Tobiasloch** [innoTUgrid/backend#55]
When calling 
`curl -X GET "http://localhost:3000/v1/kpi/scope_one_emissions/?from=2019-01-01T00:00:00.000Z&to=2019-12-31T23:59:59.999Z&interval=1month"`

the i get the response:

`[
    {
        "bucket": "2018-12-10T00:00:00Z",
        "carrier_name": "biogas",
        "value": 2849.1566250000105,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2018-12-10T00:00:00Z",
        "carrier_name": "solar",
        "value": 1556.827169999978,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-01-07T00:00:00Z",
        "carrier_name": "biogas",
        "value": 29447.959232143985,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-01-07T00:00:00Z",
        "carrier_name": "solar",
        "value": 1753.5034699714686,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-02-04T00:00:00Z",
        "carrier_name": "biogas",
        "value": 63319.32549084355,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-02-04T00:00:00Z",
        "carrier_name": "solar",
        "value": 1445.6137456113988,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-03-04T00:00:00Z",
        "carrier_name": "biogas",
        "value": 58798.67083457747,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-03-04T00:00:00Z",
        "carrier_name": "solar",
        "value": 520.1312744441257,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-04-01T00:00:00Z",
        "carrier_name": "biogas",
        "value": 35358.2213839299,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-04-01T00:00:00Z",
        "carrier_name": "solar",
        "value": 1323.5234271428926,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-04-29T00:00:00Z",
        "carrier_name": "biogas",
        "value": 26540.724937500996,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-04-29T00:00:00Z",
        "carrier_name": "solar",
        "value": 1331.561877428604,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-05-27T00:00:00Z",
        "carrier_name": "biogas",
        "value": 3318.5395982144137,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-05-27T00:00:00Z",
        "carrier_name": "solar",
        "value": 1034.661162857167,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-06-24T00:00:00Z",
        "carrier_name": "biogas",
        "value": 0.0,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-06-24T00:00:00Z",
        "carrier_name": "solar",
        "value": 851.1601783329709,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-07-22T00:00:00Z",
        "carrier_name": "biogas",
        "value": 1.170535714285759,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-07-22T00:00:00Z",
        "carrier_name": "solar",
        "value": 811.3574751428756,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-08-19T00:00:00Z",
        "carrier_name": "biogas",
        "value": 0.0,
        "unit": "kgco2eq"
    },
    {
        "bucket": "2019-08-19T00:00:00Z",
        "carrier_name": "solar",
        "value": 842.6810270769306,
        "unit": "kgco2eq"
    }
]`

the first data points are from 2018. The return of the endpoint should only contain data within the timeinterval.

**Comment by gretamaltsenko** [comment]
bitte prioritär behandeln @OleFass @tomijange @nymphbox
